# Generated by Django 3.0.6 on 2020-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200819_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
