# Generated by Django 3.0.6 on 2021-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='clothes_category',
            field=models.CharField(choices=[('TP', 'Tops'), ('CTS', 'Coats'), ('JNS', 'Jeans'), ('DRS', 'Dresses'), ('NWK', 'New Stock')], default='TP', max_length=32),
        ),
    ]
